server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.0.42/workorder?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://192.168.0.21:3306/workorder?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      maximum-pool-size: 20  #最大线程数
    dbcp2:                                        #  进行数据库连接池的配置
      min-idle: 5                                 #  数据库连接池的最小维持连接数
      initial-size: 5                             #  初始化提供的连接数
      max-total: 5                                #  最大连接数
      max-wait-millis: 200
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true

#    database-platform: org.hibernate.dialect.MySQLDialect

secretKey: myKey
#过期时间 单位天数
outTime: 15




